main: main.o 
	g++ -o main main.o

main.o: main.cpp
	g++ -c main.cpp

clean: 
	rm -f main.o

install:
	@echo do the stuff to install 
	@echo this package

help: 
	@ecgho Print out some useful help
	@echo information about using 
	@echo make with this Makefile



#This is a comment


